### ISSUE TITLE
APM Server should listen on any interface by default

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server-docker#15]
The APM Server docker image currently only listens on localhost:8200 by default.

**Comment by roncohen** [comment]
These users have seen problems: 
* https://discuss.elastic.co/t/issue-with-apm-monitoring-for-docker-containers/130110
* https://discuss.elastic.co/t/getting-econnrefused-when-calling-from-node/128917/7

Elasticsearch also defaults to 0.0.0.0: https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml#L2

**Comment by roncohen** [comment]
It's generally the case that in Docker you also need to "expose" ports to be able to access them from the host machine, so as a long as we only make this change in the apm-server docker image, and not in the apm-server default non-docker installation, we should be fine.

**Comment by jarpy** [comment]
Yep. This is really important for containers, since the traffic for the exposed ports arrives on an "ethernet" interface, not `lo`.
